title: Savir Singh
markdown: kramdown
baseurl: "/"
url: "https://savirsingh.com"

paginate: 5
paginate_path: "/posts/page:num/"

excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /posts/:title
